import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar, useTheme, Button, Link, Text } from "@nextui-org/react";
import { Layout } from '../components/Layout';
import { AcmeLogo } from '../components/AcmeLogo';

export default function Home() {

  const { isDark } = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout>
          <Navbar shouldHideOnScroll isBordered={isDark} variant="sticky">
            <Navbar.Brand>
              <AcmeLogo />
              <Text b color="inherit" hideIn="xs">
                ACME
              </Text>
            </Navbar.Brand>
            <Navbar.Content hideIn="xs" variant="underline">
              <Navbar.Link href="#">Features</Navbar.Link>
              <Navbar.Link isActive href="#">Customers</Navbar.Link>
              <Navbar.Link href="#">Pricing</Navbar.Link>
              <Navbar.Link href="#">Company</Navbar.Link>
            </Navbar.Content>
            <Navbar.Content>
              <Navbar.Link color="inherit" href="#">
                Login
              </Navbar.Link>
              <Navbar.Item>
                <Button auto flat as={Link} href="#">
                  Sign Up
                </Button>
              </Navbar.Item>
            </Navbar.Content>
          </Navbar>
        </Layout>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
