import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar, useTheme, Button, Text, Textarea, Input, Spacer, Card, Row, Switch, Link } from "@nextui-org/react";
import { Layout } from '../components/Layout';
import { AcmeLogo } from '../components/AcmeLogo';
import { SunIcon } from '../assets/icons/SunIcon';
import { MoonIcon } from '../assets/icons/MoonIcon';
import { useTheme as useNextTheme } from 'next-themes'

export default function Home() {
  const { setTheme } = useNextTheme();
  const { isDark } = useTheme();

  const collapseItems = [
    "Company",
    "Legal",
    "Team",
    "Help & Feedback",
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Shösansei Software | Custom Software For E-commerce Sellers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout>
          <Navbar shouldHideOnScroll isBordered={isDark} variant="static">
            <Navbar.Brand>
              <AcmeLogo />
              <Text b color="inherit" hideIn="xs">
                Shösansei
              </Text>
            </Navbar.Brand>
            <Navbar.Content enableCursorHighlight hideIn="xs" variant="underline">
              <Navbar.Link href="#">Features</Navbar.Link>
              <Navbar.Link href="/portfolio">Projects</Navbar.Link>
              <Navbar.Link href="#">Pricing</Navbar.Link>
              <Navbar.Link href="#">Company</Navbar.Link>
            </Navbar.Content>
            <Navbar.Toggle aria-label="toggle navigation" showIn={"xs"} />
            <Navbar.Content>
           
              <Navbar.Item>
                <Switch
                  checked={isDark}
                  size="lg"
                  onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
                  color="secondary"
                  iconOn={<SunIcon filled />}
                  iconOff={<MoonIcon filled />}
                />
              </Navbar.Item>
            </Navbar.Content>
            <Navbar.Collapse showIn={"sm"}>
              {collapseItems.map((item, index) => (
                <Navbar.CollapseItem key={item}>
                  <Link
                    color="inherit"
                    css={{
                      minWidth: "100%",
                    }}
                    href="#"
                  >
                    {item}
                  </Link>
                </Navbar.CollapseItem>
              ))}
            </Navbar.Collapse>
          </Navbar>
        </Layout>
        

      </main>
      <footer className={styles.footer}>
    
      </footer>
    </div>
  )
}
